server:
  applicationConnectors:
  - type: http
    port: 9000
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: usr_srv_user

  # the password
  password: password

  # the JDBC URL
  url: jdbc:postgresql://localhost/users_db

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the timeout before a connection validation queries fail
  validationQueryTimeout: 3s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      # The file to which current statements will be logged.
      currentLogFilename: ./logs/usr-service.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: ./logs/usr-service-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: Europe/Moscow
  loggers:
    "com.asmirnov.usrservice.resources.UserResource":
      level: DEBUG
      additive: false
      appenders:
        - type: file
          currentLogFilename: ./logs/user-resource.log
          archivedLogFilenamePattern: ./logs/user-resource-%d.log.gz
          archivedFileCount: 5